apiVersion: v2
name: k8s-ces-setup-helm-variant-02
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
#  - name: k8s-backup-operator-crd
#    version: "1.4.6"
#    repository: "oci://registry.cloudogu.com/k8s"
  - name: k8s-backup-operator
    version: "1.4.6"
    repository: "oci://registry.cloudogu.com/k8s"
#  - name: k8s-dogu-operator-crd
#    version: "2.9.0"
#    repository: "oci://registry.cloudogu.com/k8s"
  - name: k8s-dogu-operator
    version: "3.11.2"
    repository: "oci://registry.cloudogu.com/k8s"
  - name: k8s-service-discovery
    version: "2.0.0"
    repository: "oci://registry.cloudogu.com/k8s"
#  - name: k8s-snapshot-controller-crd
#    version: "8.2.1-2"
#    repository: "oci://registry.cloudogu.com/k8s"
  - name: k8s-snapshot-controller
    version: "8.2.1-2"
    repository: "oci://registry.cloudogu.com/k8s"
  - name: k8s-velero
    version: "10.0.1-2"
    repository: "oci://registry.cloudogu.com/k8s"
#  - name: k8s-blueprint-operator-crd
#    version: "1.3.0"
#    repository: "oci://registry.cloudogu.com/k8s"
  - name: k8s-blueprint-operator
    version: "2.6.0"
    repository: "oci://registry.cloudogu.com/k8s"

