doguregistry:
  endpoint: https://dogu.cloudogu.com/api/v2/dogus
  url_schema: https://dogu.cloudogu.com/api/v2/dogus_SCHEMA
  username: ""
  password: ""

registry:
  endpoint: https://registry.cloudogu.com
  username: ""
  password: ""
  email: ""

certificate:
  type: "selfsigned"
  crt: ""
  key: ""

config:
  domain:
  fqdn:
  admin_group: cesAdmin
  default_dogu: ""
  k8s:
    internal_ip: ""
    use_internal_ip: "false"
  mail_address: ""